spring:
  mvc:
    view:
      prefix: classpath:/templates/**
      suffix: .html
  freemarker:
    suffix: .html
    request-context-attribute: request
  datasource:
          name: test
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://129.204.211.236:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: root
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
server:
  port: 8080
mybatis:
  mapper-locations: classpath*:mapper/*.xml